### ISSUE TITLE
Empty page and request objets

### ISSUE THREAD

**Issue by pyby** [SRGSSR/srgnetwork-apple#11]
### Issue type

Feature request

### Description of the problem

The Play iOS project can't build with Xcode 12.5 beta 1 and beta 2. See https://github.com/SRGSSR/playsrg-apple/issues/173.
SRGLetterbox demo project as well affected.

`[SRGPage new]` and `[SRGRequest new]` were used, even if the `init` method is unavailable.
Xcode 12.5 does not allow it anymore.

Should we fix in our project or could we have an empty objet from `SRGNetwork`?

### Environment information

* Application version: Xcode 12.5
* iOS / tvOS version: Any
* Device: Any

### Reproducibility

Always reproducible

**Comment by pyby** [comment]
A proposition is available on `feature/empty-objects`.

To be discuss in the team.

**Comment by defagos** [comment]
Not really fond of having empty objects to solve what is essentially a compilation issue. It is exactly like `+new` internally, so this is just creating an alias for a method which already exists.

For this reason I think it is easier to just remove the unavailability attribute. That avoids having to document new methods (and what is meant by emptiness). Users in general use documented initializers (think about `UIView` or `UIViewController` for example, for which `-init` is not really useful).

**Comment by pyby** [comment]
Thanks to the discussion. We agreed that it's better to remove unavailability macros and expose `init.

Empty objects proposition is not adopted. I removed the branch.
